method:
  model_name: "simpl"
  
  # Global parameters
  g_num_modes: 6
  g_obs_len: 50
  g_pred_len: 60
  
  # Network parameters
  in_actor: 14
  d_actor: 128
  n_fpn_scale: 4
  in_lane: 24
  d_lane: 128
  d_rpe_in: 5
  d_rpe: 128
  d_embed: 128
  n_scene_layer: 4
  n_scene_head: 8
  dropout: 0.1
  update_edge: true
  
  # Trajectory parameters
  param_out: "bezier"  # bezier/monomial/none
  param_order: 7  # 7-th order polynomials
  
  # Loss parameters
  cls_coef: 0.1
  reg_coef: 0.9
  loss_type: 'ADE'  # 'ADE' 또는 'FDE'
  
  mgn: 0.2
  cls_th: 2.0
  cls_ignore: 0.2
  yaw_loss: true
  
  # Training parameters
  train_batch_size: 32
  eval_batch_size: 32
  max_epochs: 100
  grad_clip_norm: 1.0
  
  # Optimizer parameters
  opt: "adam"
  weight_decay: 0.0
  lr_scale_func: "none"  # none/sqrt/linear
  
  # Scheduler parameters
  scheduler: "polyline"
  init_lr: 1e-4
  milestones: [0, 5, 35, 40]
  values: [1e-4, 1e-3, 1e-3, 1e-4]
  
  # Evaluation parameters
  data_ver: "av2"
  miss_thres: 2.0

  # Pretrained model parameters
  use_pretrained: false  # Whether to use pretrained model
  pretrained_path: null  # Path to pretrained model checkpoint
  finetune_layers: []  # List of layer names to finetune (empty list means finetune all) 

#   finetune_layers: [
#     # ActorNet 관련 레이어
#     "fusion_net.actor_net.groups",
#     "fusion_net.actor_net.lateral",
#     "fusion_net.actor_net.output",
    
#     # LaneNet 관련 레이어
#     "fusion_net.lane_net.proj",
#     "fusion_net.lane_net.aggre1",
#     "fusion_net.lane_net.aggre2",
    
#     # FusionNet 관련 레이어
#     "fusion_net.proj_actor",
#     "fusion_net.proj_lane",
#     "fusion_net.proj_rpe_scene",
#     "fusion_net.sft",
    
#     # Decoder 관련 레이어
#     "decoder.multihead_proj",
#     "decoder.cls",
#     "decoder.reg"
# ]